stName=input("enter the name of the student:")
stUSN=input("enter the usn of the student:")
stMarks1=int(input("enter marks in subject1:"))
stMarks2=int(input("enter marks in subject2:"))
stMarks3=int(input("enter marks in subject3:"))
print("Student Details\n====================")
print("%12s"%("Name:"),stName)
print("%12s"%("USN:"),stUSN)
print("%12s"%("Marks1:"),stMarks1)
print("%12s"%("Marks2:"),stMarks2)
print("%12s"%("Marks3:"),stMarks3)
print("%12s"%("Total:"),stMarks1+stMarks2+stMarks3)
print("%12s"%("Percent:"),"%.2f"%((stMarks1+stMarks2+stMarks3)/3))
print("====================")
